const quizBank = {
  "HTML": [
    { question : "What does HTML stand for?", "options": ["HyperText Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyper Transfer Markup Language"], "answer": 0 },
    { question : "Who is the father of HTML?", "options": ["Tim Berners-Lee", "Brendan Eich", "Håkon Wium Lie", "James Gosling"], "answer": 0 },
    { question : "Choose the correct HTML element for the largest heading:", "options": ["<h6>", "<heading>", "<head>", "<h1>"], "answer": 3 },
    { question : "What is the correct HTML element for inserting a line break?", "options": ["<break>", "<lb>", "<br>", "<newline>"], "answer": 2 },
    { question : "Which tag is used to create a hyperlink in HTML?", "options": ["<hyperlink>", "<href>", "<a>", "<link>"], "answer": 2 },
    { question : "Which HTML attribute is used to define inline styles?", "options": ["font", "class", "style", "styles"], "answer": 2 },
    { question : "Which is the correct HTML element for inserting a background color?", "options": ["<body style=\"background-color:yellow;\">", "<background>yellow</background>", "<bg>yellow</bg>", "<body bg=yellow>"], "answer": 0 },
    { question : "How can you make a numbered list?", "options": ["<ul>", "<dl>", "<ol>", "<list>"], "answer": 2 },
    { question : "How can you make a bulleted list?", "options": ["<ol>", "<dl>", "<ul>", "<list>"], "answer": 2 },
    { question : "What is the correct HTML for adding a background color?", "options": ["<body background=\"yellow\">", "<body style=\"background-color:yellow;\">", "<background>yellow</background>", "<bg>yellow</bg>"], "answer": 1 },
    { question : "Choose the correct HTML element to define important text.", "options": ["<important>", "<b>", "<strong>", "<i>"], "answer": 2 },
    { question : "Choose the correct HTML element to define emphasized text.", "options": ["<em>", "<i>", "<italic>", "<strong>"], "answer": 0 },
    { question : "Which character is used to indicate an end tag?", "options": ["/", "*", "^", "<"], "answer": 0 },
    { question : "How can you display a picture on a webpage?", "options": ["<img src=\"image.jpg\">", "<image src=\"image.jpg\">", "<picture href=\"image.jpg\">", "<img href=\"image.jpg\">"], "answer": 0 },
    { question : "Which element defines a table row?", "options": ["<tr>", "<td>", "<th>", "<table>"], "answer": 0 },
    { question : "Which HTML element defines the title of a document?", "options": ["<meta>", "<title>", "<heading>", "<header>"], "answer": 1 },
    { question : "What does the <a> tag do?", "options": ["Creates a divider", "Defines a link", "Puts text in italics", "Adds an anchor"], "answer": 1 },
    { question : "HTML files are saved by default with which extension?", "options": [".ht", ".html", ".hml", ".htmll"], "answer": 1 },
    { question : "Which tag is used to insert an image?", "options": ["<img>", "<src>", "<link>", "<image>"], "answer": 0 },
    { question : "Which is the correct HTML element for the smallest heading?", "options": ["<h0>", "<h6>", "<h7>", "<h1>"], "answer": 1 },
    { question : "Which of the following is NOT a valid tag in HTML?", "options": ["<div>", "<footer>", "<section>", "<mainly>"], "answer": 3 },
    { question : "What is the correct HTML for creating a checkbox?", "options": ["<input type=checkbox>", "<checkbox>", "<input type=check>", "<box>"], "answer": 0 },
    { question : "Which HTML element is used for the largest text size?", "options": ["<h6>", "<big>", "<h1>", "<large>"], "answer": 2 },
    { question : "What is the purpose of <thead>, <tbody>, and <tfoot> in a table?", "options": ["Structure the table data", "Style the table with CSS", "Create links", "Insert rows only"], "answer": 0 },
    { question : "How can you create an e-mail link?", "options": ["<mail href=\"user@email.com\">", "<a href=\"mailto:user@email.com\">", "<email href=\"user@email.com\">", "<a mail=\"user@email.com\">"], "answer": 1 },
    { question : "Which HTML tag is used to define an unordered list?", "options": ["<li>", "<ul>", "<ol>", "<list>"], "answer": 1 },
    { question : "How do you insert a comment in HTML?", "options": ["<-- Comment -->", "<!-- Comment -->", "// Comment", "/* Comment */"], "answer": 1 },
    { question : "Which is the proper way to declare the document type for HTML5?", "options": ["<!doctype html>", "<doc type=html>", "<doctype html>", "<!document html>"], "answer": 0 },
    { question : "Which HTML tag is used to define an internal style sheet?", "options": ["<script>", "<style>", "<css>", "<stylesheet>"], "answer": 1 },
    { question : "How can you open a link in a new tab/browser window?", "options": ["<a href=\"url\">link</a>", "<a href=\"url\" target=\"_blank\">link</a>", "<a new=\"url\">link</a>", "<a href=\"url\" target=\"new\">link</a>"], "answer": 1 },
    { question : "Which tag is used to embed a video in HTML5?", "options": ["<movie>", "<media>", "<video>", "<embed>"], "answer": 2 },
    { question : "How do you make a text bold in HTML?", "options": ["<important>", "<strong>", "<b>", "<fat>"], "answer": 2 },
    { question : "Which HTML element is used to play audio files?", "options": ["<media>", "<video>", "<embed>", "<audio>"], "answer": 3 },
    { question : "Which tag is used to create a dropdown list?", "options": ["<dropdown>", "<select>", "<list>", "<input type=\"dropdown\">"], "answer": 1 },
    { question : "Which attribute is used to uniquely identify an HTML element?", "options": ["class", "id", "name", "key"], "answer": 1 },
    { question : "Which HTML feature is used for responsive web design?", "options": ["<responsive>", "<viewport>", "<meta name=\"viewport\">", "<scale>",], "answer": 2 },
    { question : "What is the purpose of the <form> element?", "options": ["For tables", "For scripts", "To collect user input", "To format text"], "answer": 2 },
    { question : "What is the default value of the position property in HTML?", "options": ["fixed", "relative", "static", "absolute"], "answer": 2 },
    { question : "Which attribute in the <img> tag is used for alternate text?", "options": ["alt", "title", "name", "text"], "answer": 0 },
    { question : "Which HTML tag is used to create a horizontal line?", "options": ["<hr>", "<line>", "<break>", "<hline>"], "answer": 0 },
    { question : "Which is the correct way to create an ordered list?", "options": ["<ol>", "<ul>", "<dl>", "<list>"], "answer": 0 },
    { question : "Which tag creates a checkbox in HTML?", "options": ["<box>", "<input type=\"checkbox\">", "<checkbox>", "<input type=\"check\">"], "answer": 1 },
    { question : "Which HTML tag is semantic?", "options": ["<span>", "<div>", "<header>", "<b>"], "answer": 2 },
    { question : "What does the <meta> tag do?", "options": ["Provides metadata about the HTML document", "Displays images", "Creates a link", "Includes scripts"], "answer": 0 },
    { question : "What does the <input type=\"radio\"> create?", "options": ["Number picker", "Checkbox", "Radio button", "Text box"], "answer": 2 },
    { question : "Which tag defines emphasized text?", "options": ["<italic>", "<em>", "<i>", "<strong>"], "answer": 1 },
    { question : "What is the correct HTML for making text italic?", "options": ["<italic>", "<i>", "<em>", "<ii>"], "answer": 1 },
    { question : "What is the latest HTML standard as of 2025?", "options": ["HTML3", "HTML4", "HTML5", "HTML6"], "answer": 2 },
    { question : "Which tag represents a navigation section?", "options": ["<nav>", "<navigate>", "<navigation>", "<main>"], "answer": 0 },
    { question : "Which tag defines a caption for a table?", "options": ["<title>", "<caption>", "<summary>", "<thead>"], "answer": 1 },
    { question : "How do you specify a comment in HTML?", "options": ["// This is a comment", "<!-- This is a comment -->", "# This is a comment", "* This is a comment *"], "answer": 1 },
    { question : "Which doctype declaration is correct for HTML5?", "options": ["<!DOCTYPE html>", "<!DOCTYPE HTML PUBLIC>", "<!DOCTYPE html5>", "<!HTML5>"], "answer": 0 },
    { question : "Which attribute is used on <input> elements to make them mandatory?", "options": ["required", "mandatory", "validate", "mustfill"], "answer": 0 }
  ],
  "CSS": [
    { question : "What does CSS stand for?", "options": ["Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], "answer": 0 },
    { question : "Which HTML tag is used to define an internal style sheet?", "options": ["<css>", "<script>", "<style>", "<stylesheet>"], "answer": 2 },
    { question : "Which is the correct CSS syntax?", "options": ["body:color=black;", "{body:color=black;}", "body {color: black;}", "body = color (black);"], "answer": 2 },
    { question : "Where is an external CSS file referenced in HTML?", "options": ["In the <body> section", "At the end of the document", "Within the <footer>", "In the <head> section"], "answer": 3 },
    { question : "Which property is used to change the text color?", "options": ["font-color", "color", "text-color", "fgcolor"], "answer": 1 },
    { question : "How do you select an element with id 'demo'?", "options": [".demo", "demo", "#demo", "*demo"], "answer": 2 },
    { question : "How do you select elements with class 'test'?", "options": ["test", ".test", "#test", "*test"], "answer": 1 },
    { question : "Which property changes the background color?", "options": ["background-color", "color", "bgcolor", "backgroundImage"], "answer": 0 },
    { question : "How do you make each word in a text start with a capital letter?", "options": ["text-transform:capitalize;", "text-style:capitalize;", "transform:capitalize;", "capitalize:words;"], "answer": 0 },
    { question : "How do you select all p elements inside a div?", "options": ["div p", "div.p", "div-p", "div+p"], "answer": 0 },
    { question : "Which property controls the text size?", "options": ["font-style", "text-size", "font-size", "text-style"], "answer": 2 },
    { question : "How do you make the text bold?", "options": ["font-weight:bold;", "font:bold;", "text:bold;", "weight:bold;"], "answer": 0 },
    { question : "How do you display a border like this: The top border = 10px, bottom border = 5px, left border = 20px and right border = 1px?", "options": ["border-width:10px 1px 5px 20px;", "border-width:10px 20px 5px 1px;", "border-width:10px 5px 20px 1px;", "border-width:10px 1px 20px 5px;"], "answer": 0 },
    { question : "How do you make a list that lists its items with squares?", "options": ["list-type:square;", "list-style-type:circle;", "list-style-type:square;", "list: square;"], "answer": 2 },
    { question : "How do you select all elements with a class 'done' inside any element with class 'box'?", "options": [".box.done", ".box .done", ".done .box", "#box .done"], "answer": 1 },
    { question : "Which property adds space between the element's border and inner content?", "options": ["margin", "padding", "spacing", "border-spacing"], "answer": 1 },
    { question : "How do you make the background image NOT repeat?", "options": ["background:no-repeat;", "background-repeat:no-repeat;", "repeat:none;", "bg-repeat:off;"], "answer": 1 },
    { question : "What is the value for font-size to set it to 150%?", "options": ["font-size:150;", "font-size:1.5;", "font-size:150%;", "font-size:150em;"], "answer": 2 },
    { question : "Which CSS property controls the space between letters?", "options": ["character-spacing", "text-spacing", "letter-spacing", "line-spacing"], "answer": 2 },
    { question : "Which property is used for rounded corners?", "options": ["corner-radius", "border-radius", "round-border", "radius"], "answer": 1 },
    { question : "Which values are valid for position property?", "options": ["static, relative, absolute, fixed, sticky", "block, inline, flex, grid", "float, clear, none", "all of the above"], "answer": 0 },
    { question : "How do you remove the underline from an anchor element?", "options": ["text-decoration:none;", "underline:no;", "decoration:none;", "text-underline:none;"], "answer": 0 },
    { question : "When using 'float: left', the element:", "options": ["Is centered", "Disappears", "Moves to left side", "Moves to right side"], "answer": 2 },
    { question : "How do you select only p elements with class 'note'?", "options": ["p.note", ".note p", "note.p", "p#note"], "answer": 0 },
    { question : "Which CSS property makes the text italic?", "options": ["font-italic", "font:italic;", "font-style:italic;", "style:italic;"], "answer": 2 },
    { question : "How to write a comment in CSS?", "options": ["// this is a comment", "<!-- this is a comment -->", "# this is a comment", "/* this is a comment */"], "answer": 3 },
    { question : "What does 'display: none' do?", "options": ["Hides element and removes from layout", "Turns element red", "Makes element lowercase", "Centers the element"], "answer": 0 },
    { question : "What is the default value of the display property?", "options": ["inline", "block", "none", "inline-block"], "answer": 0 },
    { question : "Which property is used to align text?", "options": ["text-align", "text-style", "align", "font-align"], "answer": 0 },
    { question : "Which CSS property is used for shadow around a box?", "options": ["shadow", "box-shadow", "text-shadow", "border-shadow"], "answer": 1 },
    { question : "What value of position should be used to fix an element at the window's top?", "options": ["static", "absolute", "fixed", "relative"], "answer": 2 },
    { question : "How do you select all <a> elements with target='_blank'?", "options": ["a[target='_blank']", "a.target='_blank'", "a[blank]", "a(target='_blank')"], "answer": 0 },
    { question : "What does the z-index property do?", "options": ["Changes opacity", "Sets the order of stacking elements", "Centers content", "Sets column count"], "answer": 1 },
    { question : "How do you group selectors?", "options": ["Separate each selector by comma", "Space between selectors", "Selectors: group", "Selectors; group"], "answer": 0 },
    { question : "How do you apply a style to all <p> elements inside <div>?", "options": ["div p", "div.p", "p.div", "div+p"], "answer": 0 },
    { question : "What does the :hover pseudo-class do?", "options": ["Styles on mouse hover", "Styles when clicked", "Styles when loading", "None of these"], "answer": 0 },
    { question : "Which measurement unit is relative to the font-size of the root element?", "options": ["px", "cm", "em", "rem"], "answer": 3 },
    { question : "Which CSS property controls the left margin of an element?", "options": ["margin-left", "padding-left", "left-margin", "spacing-left"], "answer": 0 },
    { question : "Which is NOT a valid value for the font-style property?", "options": ["italic", "oblique", "bold", "normal"], "answer": 2 },
    { question : "Which property is used to create space between lines of text?", "options": ["line-height", "letter-spacing", "text-indent", "text-spacing"], "answer": 0 },
    { question : "What does the overflow property do?", "options": ["Hides background", "Controls content outside an element", "Changes opacity", "Sets transition"], "answer": 1 },
    { question : "Which CSS property is used for transitions?", "options": ["transition", "shift", "move", "effect"], "answer": 0 },
    { question : "Which property creates a flexible layout structure?", "options": ["flex", "display: flex", "layout", "inline-flex"], "answer": 1 },
    { question : "Which property controls the transparency level?", "options": ["visibility", "opacity", "alpha", "transparency"], "answer": 1 },
    { question : "Which symbol is used for 'descendant' selectors?", "options": ["+", ">", "~", " "], "answer": 3 },
    { question : "Which pseudo-class matches the first <li> element?", "options": [":hover", ":first-child", ":first", ":first-li"], "answer": 1 },
    { question : "Which value makes an element not visible but still occupies space?", "options": ["display: none", "visibility: hidden", "opacity: 0", "hidden: true"], "answer": 1 },
    { question : "Which property makes an element a grid container?", "options": ["display: grid", "grid: true", "grid-container", "set-grid"], "answer": 0 },
    { question : "Which property sets how table cells, rows, and columns are displayed?", "options": ["table-layout", "cell-layout", "display", "table-display"], "answer": 0 },
    { question : "Which is NOT a valid CSS preprocessor?", "options": ["Sass", "LESS", "Stylus", "Classy"], "answer": 3 },
    { question : "Which is correct to set all padding values to zero?", "options": ["padding: 0;", "padding = 0;", "set-padding: 0;", "padding 0"], "answer": 0 }
  ],
  "JavaScript": [
    {question :"Inside which HTML element do we put JavaScript code?","options":["<script>","<js>","<scripting>","<javascript>"],"answer":0},
    {question :"What is the correct syntax for referring to an external script called 'app.js'?","options":["<script src='app.js'>","<script href='app.js'>","<script ref='app.js'>","<script name='app.js'>"],"answer":0},
    {question :"How do you write 'Hello World' in an alert box?","options":["msg('Hello World');","alert('Hello World');","alertBox('Hello World');","msgBox('Hello World');"],"answer":1},
    {question :"How do you create a function in JavaScript?","options":["function:myFunction()","function myFunction()","create myFunction()","def myFunction()"],"answer":1},
    {question :"How do you call a function named 'myFunction'?","options":["call myFunction()","call function myFunction()","myFunction()","Call.myFunction()"],"answer":2},
    {question :"How can you add a comment in JavaScript?","options":["//This is a comment","<!--This is a comment-->","| This is a comment |","# This is a comment"],"answer":0},
    {question :"What is the correct way to write a JavaScript array?","options":["var colors = (1:'red',2:'green',3:'blue')","var colors = ['red','green','blue']","var colors = 'red','green','blue'","var colors = {'red', 'green', 'blue'}"],"answer":1},
    {question :"How do you round the number 7.25 to the nearest integer?","options":["Math.rnd(7.25)","Math.round(7.25)","round(7.25)","rnd(7.25)"],"answer":1},
    {question :"How do you find the number with the highest value of x and y?","options":["Math.max(x, y)","top(x, y)","Math.top(x, y)","ceil(x, y)"],"answer":0},
    {question :"What is the correct JavaScript syntax to change the text of element with id='demo'?","options":["document.getElementById('demo').textContent = 'Hello';","demo.innerHTML = 'Hello';","document.getElement('demo').innerHTML = 'Hello';","document.getElementById('demo').innerHTML = 'Hello';"],"answer":3},
    {question :"Which event occurs when the user clicks on an HTML element?","options":["onmouseclick","onchange","onclick","onmouseover"],"answer":2},
    {question :"How do you declare a JavaScript variable?","options":["v carName;","variable carName;","var carName;","str carName;"],"answer":2},
    {question :"What is the correct operator to assign a value to a variable?","options":["-","*","=","x"],"answer":2},
    {question :"What will the following code output? console.log(typeof []);","options":["'object'","'array'","'list'","'array object'"],"answer":0},
    {question :"Which operator is used to compare both value and type in JavaScript?","options":["==","===","=","!="],"answer":1},
    {question :"How can you detect the client's browser name?","options":["navigator.appName","browser.name","client.navName","window.browser"],"answer":0},
    {question :"How do you write an IF statement in JavaScript?","options":["if i = 5 then","if i == 5 then","if (i == 5)","if i = 5"],"answer":2},
    {question :"How to write an IF statement for executing code if 'i' is NOT equal to 5?","options":["if (i != 5)","if i <> 5","if (i <> 5)","if i =! 5"],"answer":0},
    {question :"How does a WHILE loop start?","options":["while (i <= 10; i++)","while (i <= 10)","while i = 1 to 10","while (i++ <= 10)"],"answer":1},
    {question :"How does a FOR loop start?","options":["for (i <= 5; i++)","for (i=0; i<=5)","for i = 1 to 5","for (i=0; i<=5; i++)"],"answer":3},
    {question :"How can you add a new element at the end of an array?","options":["arr.last('value')","arr.push('value')","arr.add('value')","arr[+1] = 'value'"],"answer":1},
    {question :"How do you remove the last element from an array?","options":["arr.remove()","arr.pop()","arr.delete()","arr.cut()"],"answer":1},
    {question :"Which statement will return the type of variable 'a'?","options":["typeof(a)","type(a)","a.type()","typeof a"],"answer":3},
    {question :"Which method joins array elements into a single string?","options":["array.connect()","array.join()","array.concat()","array.toString()"],"answer":1},
    {question :"What keyword is used to stop a loop in JavaScript?","options":["break","stop","exit","pause"],"answer":0},
    {question :"Which is a valid way to create an object in JavaScript?","options":["var obj={};","var obj=new Object();","Both 1 and 2","None of these"],"answer":2},
    {question :"Which function parses a JSON string into a JavaScript object?","options":["JSON.parse()","parseJSON()","JSON.stringify()","obj.fromJSON()"],"answer":0},
    {question :"How do you write 'Hello' to the browser's console?","options":["print('Hello')","console.log('Hello')","log.console('Hello')","out('Hello')"],"answer":1},
    {question :"Which is true for const variables?","options":["Cannot be reassigned","Block scoped","Must be initialized","All of the above"],"answer":3},
    {question :"Which statement is used to skip the current iteration of a loop?","options":["break","continue","skip","next"],"answer":1},
    {question :"How do you check if 'x' is an array?","options":["Array.isArray(x)","x instanceof Array","x.typeof('array')","Both 1 and 2"],"answer":3},
    {question :"Which built-in method sorts the elements of an array?","options":["sort()","order()","arrange()","list()"],"answer":0},
    {question :"What is the correct syntax for an arrow function that returns x*2?","options":["(x) -> x*2","x => x*2","x => {return x*2}","Both 2 and 3"],"answer":3},
    {question :"What does the 'this' keyword refer to inside a method?","options":["The current object","The global object","The previous object","The prototype"],"answer":0},
    {question :"Which is the correct way to write a class in JavaScript?","options":["class MyClass {}","MyClass() {}","new class MyClass {}","define MyClass() {}"],"answer":0},
    {question :"What does '===' operator do in JavaScript?","options":["Assigns","Compares only value","Compares value and type","Compares reference"],"answer":2},
    {question :"Which method can be used to convert a string to lowercase?","options":["str.toLower()","str.lower()","str.toLowerCase()","str.toLowercase()"],"answer":2},
    {question :"What will '2' + 2 evaluate to in JavaScript?","options":["4","22","'22'","Error"],"answer":2},
    {question :"How do you write a single line comment?","options":["<!-- comment -->","// comment","** comment **","# comment"],"answer":1},
    {question :"Which method can be used to filter an array?","options":["filter()","map()","find()","sort()"],"answer":0},
    {question :"What is 'NaN' in JavaScript?","options":["A type of null","A pre-defined object","Indicates Not-a-Number","A function"],"answer":2},
    {question :"How do you find the length of an array?","options":["array.length()","array.count","array.size","array.length"],"answer":3},
    {question :"Which function can schedule code to run after a delay?","options":["setTimeout()","setInterval()","schedule()","wait()"],"answer":0},
    {question :"What will typeof null return?","options":["'object'","'null'","'undefined'","'none'"],"answer":0},
    {question :"What does JSON.stringify() do?","options":["Parses a string as JSON","Converts a value to a JSON string","Saves to a file","None of the above"],"answer":1},
    {question :"What is a closure in JavaScript?","options":["A type of loop","A function with preserved scope","A method argument","An error"],"answer":1},
    {question :"What is the output of \"5\" - 1?","options":["4","'51'","NaN","Error"],"answer":0},
    {question :"Which object represents the browser window?","options":["document","window","screen","navigator"],"answer":1},
    {question :"Which symbol is used for strict not equal?","options":["!==","!=","=!=","/=!"],"answer":0},
    {question :"How do you prevent default form submission?","options":["preventDefault()","stopDefault()","return false","Both 1 and 3"],"answer":3}
  ],
  "React": [
    {question :"What is React?","options":["Server-side framework","User interface library","Database","Programming language"],"answer":1},
    {question :"Who developed React?","options":["Google","Facebook","Microsoft","Twitter"],"answer":1},
    {question :"What is a component in React?","options":["Reusable piece of UI","Database function","CSS class","Build tool"],"answer":0},
    {question :"How do you create a functional component?","options":["function MyComp() {}","class MyComp extends React.Component {}","Both 1 and 2","None"],"answer":2},
    {question :"What hook is used to manage state in functional components?","options":["useState","useEffect","useRef","useMemo"],"answer":0},
    {question :"JSX stands for:","options":["JavaScript Extension","Java Syntax Extension","JavaScript XML","Java XML"],"answer":2},
    {question :"Which method is used to render elements to the DOM?","options":["ReactDOM.render()","renderDOM()","React.render()","setRender()"],"answer":0},
    {question :"What does 'props' stand for?","options":["Properties","Properties of style","Project objects","Project properties"],"answer":0},
    {question :"How are props passed to a component?","options":["As arguments","Via function call","As attributes","With setState"],"answer":2},
    {question :"What is the virtual DOM?","options":["A copy of the real DOM","A browser feature","A debugging tool","A JavaScript object"],"answer":0},
    {question :"Which hook runs code after component renders?","options":["useEffect","useState","useClass","useUpdate"],"answer":0},
    {question :"How do you update state with useState?","options":["Directly modify the variable","Call the setter function","Modify props","Call useEffect"],"answer":1},
    {question :"Which key is required when rendering lists?","options":["key","listKey","id","index"],"answer":0},
    {question :"How do you perform side effects in functional components?","options":["useEffect","useState","componentDidMount","componentWillUnmount"],"answer":0},
    {question :"How do you pass data from child to parent?","options":["Use props","Use state","Callback function as prop","Direct assignment"],"answer":2},
    {question :"Which package do you import for routing?","options":["react-router-dom","react-dom-router","react-router","router-dom"],"answer":0},
    {question :"How to conditionally render in JSX?","options":["if-else statements","Ternary operators or &&","switch inside JSX","condition attribute"],"answer":1},
    {question :"Which syntax is used to embed a JavaScript expression in JSX?","options":["{{}}","{}","[]","()"],"answer":1},
    {question :"How to create a context in React?","options":["React.createContext()","useContext()","createContext()","React.useContext()"],"answer":0},
    {question :"Which hook avoids unnecessary re-renders?","options":["useMemo","useRef","useEffect","useReducer"],"answer":0},
    {question :"Which React API is used for forward refs?","options":["React.forwardRef","useRef","createRef","forwardRefOnly"],"answer":0},
    {question :"What is the use of 'key' prop in React lists?","options":["Uniquely identifies elements","Sorts the list","Filters the list","Provides styling"],"answer":0},
    {question :"Which method can NOT be used in functional components?","options":["componentDidMount","useEffect","useState","useRef"],"answer":0},
    {question :"Which hook is suitable for global state management?","options":["useContext","useRef","useState","useMemo"],"answer":0},
    {question :"How do you create a ref in React?","options":["useRef","useEffect","createRef","useMemo"],"answer":0},
    {question :"How do you access props in a class component?","options":["this.props","props","useProps","props()"],"answer":0},
    {question :"What happens when setState is called?","options":["Component re-renders","State is deleted","Nothing changes","New component is added"],"answer":0},
    {question :"What does React.memo do?","options":["Memoizes a component","Adds side effects","Creates context","Fetches data"],"answer":0},
    {question :"Which lifecycle method fetches data after mounting a class component?","options":["componentDidMount","componentWillMount","constructor","render"],"answer":0},
    {question :"How to handle forms in React?","options":["Controlled components","Uncontrolled components","Refs","All of the above"],"answer":3},
    {question :"What is an uncontrolled component?","options":["DOM handles form data","Uses state","Uses context","Always re-renders"],"answer":0},
    {question :"Which hook can store mutable values?","options":["useRef","useState","useCallback","useEffect"],"answer":0},
    {question :"How do you optimize performance in React?","options":["Code splitting","React.memo","Lazy loading","All of the above"],"answer":3},
    {question :"React state updates are:","options":["Asynchronous","Synchronous","Both","None"],"answer":0},
    {question :"Which is true about keys in React lists?","options":["Should be unique","Can repeat","Not required","Can use random"],"answer":0},
    {question :"What is a Higher Order Component (HOC)?","options":["Component returning a function","Function returning a component","Component rendering another component","Function returning another function"],"answer":1},
    {question :"What does useReducer return?","options":["State and dispatch","State only","Dispatch only","Nothing"],"answer":0},
    {question :"Which hook is used for lazy initialization of state?","options":["useState(() => value)","useEffect","useRef","useCallback"],"answer":0},
    {question :"How do you handle errors in React?","options":["Error boundaries","Try-catch in render","Using alert","Ignoring errors"],"answer":0},
    {question :"When should you cleanup side effects?","options":["In useEffect's return function","In the start of useEffect","In render","Nowhere"],"answer":0},
    {question :"React keys are only required for:","options":["Siblings in a list","Root element","Props","Ref"],"answer":0},
    {question :"What is Prop Drilling in React?","options":["Passing data through many levels","Drilling holes in props","Creating props with drills","None of above"],"answer":0},
    {question :"How do you install React using npm?","options":["npm install react","react install npm","npm react install","install npm react"],"answer":0},
    {question :"Which attribute should you use for accessibility in React?","options":["aria-*","assist-*","role-*","all of the above"],"answer":0},
    {question :"How to handle events in React?","options":["CamelCase event handlers","SnakeCase event handlers","event='handler' style","handler = event"],"answer":0},
    {question :"useEffect hook can return:","options":["A cleanup function","A value to the component","Nothing","A React element"],"answer":0},
    {question :"How do you prevent re-render for a functional component?","options":["React.memo","shouldComponentUpdate","useRef","None"],"answer":0},
    {question :"Which method lets you render children in props?","options":["props.children","props.render","props.child","this.children"],"answer":0}
  ],
  "Node.js": [
    {question :"What is Node.js?","options":["A JS framework","A browser","A JavaScript runtime","A DBMS"],"answer":2},
    {question :"Node.js is built on which JS engine?","options":["SpiderMonkey","V8","JavaScriptCore","Chakra"],"answer":1},
    {question :"What is npm?","options":["Node Package Manager","Node Project Manager","Node Private Modules","Node’s Plugin Manager"],"answer":0},
    {question :"How do you import a module in Node.js?","options":["import","require()","include()","fetch()"],"answer":1},
    {question :"Which module is used to create a server?","options":["http","url","server","net"],"answer":0},
    {question :"How can you read a file in Node.js?","options":["fs.read()","fs.readFile()","read.file()","fs.file()"],"answer":1},
    {question :"What does EventEmitter do?","options":["Manage events","Display images","Interact with the user","Parse JSON"],"answer":0},
    {question :"process.argv returns what?","options":["Node.js version","Command line arguments","Current Dir","Port"],"answer":1},
    {question :"Which is NOT a valid Node.js module?","options":["fs","http","url","request"],"answer":3},
    {question :"How do you send a response in HTTP server?","options":["res.send()","res.write()","console.send()","request.send()"],"answer":1},
    {question :"Global object in Node.js is:","options":["window","process","global","this"],"answer":2},
    {question :"Which method writes to a file asynchronously?","options":["fs.writeSync","fs.writeFile","fs.writeFileSync","fs.write"],"answer":1},
    {question :"How do you export a function in Node.js?","options":["export function","module.exports","exports.function","define"],"answer":1},
    {question :"Which command initializes a new Node app?","options":["node init","npm start","npm init","node start"],"answer":2},
    {question :"Which package is used for routing in ExpressJS?","options":["express","router","path","route"],"answer":0},
    {question :"What is the default scope in Node.js?","options":["Local","Global","Closure","Module"],"answer":3},
    {question :"Which protocol does Node.js use for web servers?","options":["HTTP","FTP","SSH","SMTP"],"answer":0},
    {question :"How do you install a package globally?","options":["npm install -g package","npm -gi package","npm global install package","npm add package"],"answer":0},
    {question :"Which command lists globally installed npm packages?","options":["npm list","npm -g list","npm list -g","npm g-list"],"answer":2},
    {question :"What happens if you call require() twice for the same file?","options":["Error","Only loaded once","Loads twice","None of these"],"answer":1},
    {question :"What is a callback?","options":["A variable","A function passed as argument","A loop","An array"],"answer":1},
    {question :"Which is true about Node.js?","options":["Single-threaded","Non-blocking IO","Event-driven","All of these"],"answer":3},
    {question :"How do you handle errors in async functions?","options":["try-catch","catch block","error parameter","Both 1 and 3"],"answer":3},
    {question :"Which global object helps with file paths?","options":["fs","path","dir","file"],"answer":1},
    {question :"How do you install express?","options":["npm install express","install express","express install","npm get express"],"answer":0},
    {question :"What is REPL in Node.js?","options":["Read Eval Print Loop","Run Every Program Logic","Repeat Every Page Load","Run Event Print Loop"],"answer":0},
    {question :"What does require('module') return?","options":["Module instance","String","Boolean","File path"],"answer":0},
    {question :"Which function schedules code for later execution?","options":["setTimeout","schedule","timer","delay"],"answer":0},
    {question :"Which is NOT a core module?","options":["http","fs","os","express"],"answer":3},
    {question :"Which method terminates process?","options":["end()","process.end()","process.exit()","exit()"],"answer":2},
    {question :"Which command updates all packages?","options":["npm update","update npm","npm all update","update all"],"answer":0},
    {question :"How can you get environment variables?","options":["env.vars","process.env","os.env","env.get"],"answer":1},
    {question :"Which method parses JSON in Node?","options":["JSON.parse","parse.JSON","JSON.toObject","parseJSON"],"answer":0},
    {question :"Which Node version manager is widely used?","options":["nvm","vm","nodemgr","nodenv"],"answer":0},
    {question :"How do you check Node.js version?","options":["node version","node -v","npm -v","version node"],"answer":1},
    {question :"Which command runs an app in development?","options":["npm start","node app.js","Both 1 and 2","npm run dev"],"answer":2},
    {question :"Which function schedules code to repeat?","options":["setInterval","setRepeat","setTimeout","interval"],"answer":0},
    {question :"Which object holds HTTP headers for a request?","options":["req.head","req.headers","request.headers","req.header"],"answer":1},
    {question :"Which module is required for cryptography?","options":["crypto","secure","encrypt","hash"],"answer":0},
    {question :"Which port does HTTP use by default?","options":["80","3000","8080","443"],"answer":0},
    {question :"How do you write data to the console?","options":["console.write","console.log","System.out","log.console"],"answer":1},
    {question :"Which option creates a new buffer?","options":["Buffer.alloc","Buffer.create","NewBuffer()","Buffer()"],"answer":0},
    {question :"How do you watch for file changes?","options":["fs.watch","fs.observe","fs.listen","watch.file"],"answer":0},
    {question :"Which statement is true about streams?","options":["Can be readable","Can be writable","Can be both","All are true"],"answer":3},
    {question :"Which command uninstalls an npm package?","options":["npm uninstall pkg","npm remove pkg","npm delete pkg","All of above"],"answer":3},
    {question :"Which argument accesses the first user parameter in command line args?","options":["process.argv[2]","process.argv[1]","process[2]","argv[2]"],"answer":0},
    {question :"Which method creates a directory?","options":["fs.mkdir","fs.dir","fs.createDir","fs.directory"],"answer":0},
    {question :"How can you exit a REPL session?","options":["exit","Ctrl+C","Ctrl+D","Both 2 and 3"],"answer":3}
  ],
  "MongoDB": [
    {question :"What type of database is MongoDB?","options":["Relational","Hierarchical","NoSQL","File-based"],"answer":2},
    {question :"Which format does MongoDB use for data storage?","options":["XML","JSON/BSON","CSV","YAML"],"answer":1},
    {question :"Default port for MongoDB is:","options":["27017","3306","1433","1521"],"answer":0},
    {question :"Which command lists all databases?","options":["show dbs","list dbs","db.show()","dbs"],"answer":0},
    {question :"How to select a database in MongoDB shell?","options":["use dbname","db.use('dbname')","select dbname","switch dbname"],"answer":0},
    {question :"Which command shows all collections in a database?","options":["show collections","list collections","db.showCollections()","db.show()"],"answer":0},
    {question :"To insert a document into collection 'users', use:","options":["db.users.insert({})","insert db.users({})","users.db.insert({})","db.insert.users({})"],"answer":0},
    {question :"Method to find all documents in 'students'?","options":["db.students.find()","db.students.show()","find.students()","students.findAll()"],"answer":0},
    {question :"Which command removes a document?","options":["db.coll.remove({})","db.coll.drop({})","db.coll.delete({})","db.coll.destroy({})"],"answer":0},
    {question :"Which index is created automatically on a collection?","options":["_id","name","autoid","primary"],"answer":0},
    {question :"How do you update a document?","options":["db.coll.update()","db.coll.edit()","db.coll.modify()","coll.db.update()"],"answer":0},
    {question :"How can you limit number of results?","options":[".limit() method",".reduce() method","limit: in find","show limit"],"answer":0},
    {question :"What method removes an entire collection?","options":[".remove()",".drop()",".delete()",".destroy()"],"answer":1},
    {question :"Which is not a valid MongoDB data type?","options":["String","Integer","Blob","Array"],"answer":2},
    {question :"Which shell command ends a session?","options":["exit","quit()","close()","Both 1 and 2"],"answer":3},
    {question :"Which operator matches values in an array?","options":["$in","$array","$eq","$match"],"answer":0},
    {question :"Which function returns the number of documents?","options":["count()","find()","len()","size()"],"answer":0},
    {question :"Which is used for sorting documents?","options":["sort()","order()","arrange()","setOrder()"],"answer":0},
    {question :"Which is true for replica sets?","options":["Provide redundancy","Single node only","Block reads","None"],"answer":0},
    {question :"Which query operator is used for pattern matching?","options":["$regex","$pattern","$like","$match"],"answer":0},
    {question :"Which aggregation stage groups data?","options":["$group","$aggregate","$sort","$match"],"answer":0},
    {question :"Which command creates an index?","options":["db.coll.createIndex()","db.coll.setIndex()","db.coll.index()","db.coll.addIndex()"],"answer":0},
    {question :"In sharded clusters, what is required?","options":["Shard key","Replica set","Backup","Restore"],"answer":0},
    {question :"Which is NOT a valid MongoDB shell command?","options":["db.createCollection()","db.makeCollection()","db.cloneCollection()","db.copyDatabase()"],"answer":1},
    {question :"Which operator checks if a value is greater than another?","options":["$gt","$gte","$ne","$lt"],"answer":0},
    {question :"How do you check server status?","options":["db.serverStatus()","show status","serverStatus()","db.status()"],"answer":0},
    {question :"Which method renames a collection?","options":["renameCollection()","db.coll.renameCollection()","db.coll.rename()","setCollectionName()"],"answer":2},
    {question :"Which operator checks for inequality?","options":["$ne","$eq","$not","$neq"],"answer":0},
    {question :"A document in MongoDB is analogous to:","options":["Row in RDBMS","Table","Column","View"],"answer":0},
    {question :"Field that uniquely identifies a document in MongoDB is:","options":["_id","primary","unique","key"],"answer":0},
    {question :"What data type stores binary data?","options":["Binary","BinData","Blob","BinaryData"],"answer":1},
    {question :"Which method removes all documents from a collection?","options":["remove({})","delete({})","truncate()","drop()"],"answer":0},
    {question :"What do you use for schema validation?","options":["Validator","Schema","ValidationObject","Rule"],"answer":0},
    {question :"What does GridFS do?","options":["Stores large files","Deletes files","Indexes files","Names files"],"answer":0},
    {question :"Which operator checks for equality?","options":["$eq","$equal","$='","equals"],"answer":0},
    {question :"Which function is used in transactions?","options":["startSession()","begin()","transact()","startTransaction()"],"answer":0},
    {question :"What does .explain() provide?","options":["Query plan","Document details","Collection stats","Index stats"],"answer":0},
    {question :"Which storage engine is default in MongoDB?","options":["WiredTiger","MMAPv1","InnoDB","LevelDB"],"answer":0},
    {question :"Which operator selects documents where value is less than?","options":["$lt","$lte","$min","$less"],"answer":0},
    {question :"Which property is used for embedded arrays?","options":["Array","Document","List","SubDoc"],"answer":0},
    {question :"How do you check collection stats?","options":["db.coll.stats()","stats()","db.stats()","coll.stats()"],"answer":0},
    {question :"Which method returns a random document?","options":["$sample","$rand","$random","$pick"],"answer":0},
    {question :"A collection is:","options":["A group of documents","A database","A field","A node"],"answer":0},
    {question :"Which command creates a backup?","options":["mongodump","mongodb-backup","mongodb.save()","backup.db()"],"answer":0},
    {question :"Which operator performs logical AND?","options":["$and","$or","$not","$all"],"answer":0},
    {question :"How do you increase write concern?","options":["Set w in options","Set writeConcern","Use safe mode","Set writeOption"],"answer":0},
    {question :"Which tool restores backup?","options":["mongorestore","mongo-restore","mongoundo","restore"],"answer":0},
    {question :"What command drops a database?","options":["db.dropDatabase()","dropDB()","deleteDatabase()","db.removeDB()"],"answer":0},
    {question :"Which index supports text search?","options":["text","txt","string","fulltext"],"answer":0}
  ],
};